package pluginapply

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/ailtonmacedo/gosvc/internal/generator"
	"github.com/ailtonmacedo/gosvc/internal/manifest"
	"github.com/ailtonmacedo/gosvc/internal/plugin"
	"github.com/ailtonmacedo/gosvc/internal/project"
	"github.com/ailtonmacedo/gosvc/internal/projectcheck"
)

func TestRunAppliesPluginAtomicallyAndPreservesItDuringRegeneration(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("shell fixture")
	}
	projectDir, config := generatedProject(t)
	writePlugin(t, projectDir, "audit", `#!/bin/sh
read request
case "$GOSVC_PLUGIN_ACTION" in
  validate) printf '%s\n' '{"protocol_version":1,"diagnostics":[{"severity":"info","message":"audit is valid"}]}' ;;
  contribute) printf '%s\n' '{"protocol_version":1,"contribution":{"features":["trail"],"artifacts":[{"path":"internal/audit/audit.gen.go","content":"// Code generated by audit. DO NOT EDIT.\npackage audit\n","mode":420,"ownership":"generated"},{"path":"docs/AUDIT.md","content":"# Audit\n","mode":420,"ownership":"user"}]}}' ;;
esac
`)

	dryRun, err := Run(context.Background(), Options{ProjectDir: projectDir, PluginName: "audit", FrameworkVersion: "1.0.0", DryRun: true, Timeout: time.Second})
	if err != nil {
		t.Fatal(err)
	}
	if dryRun.Applied || dryRun.ManifestAction != generator.ActionUpdate {
		t.Fatalf("dry run = %+v", dryRun)
	}
	if _, err := os.Stat(filepath.Join(projectDir, "internal", "audit", "audit.gen.go")); !os.IsNotExist(err) {
		t.Fatalf("dry run wrote artifact: %v", err)
	}

	result, err := Run(context.Background(), Options{ProjectDir: projectDir, PluginName: "audit", FrameworkVersion: "1.0.0", Timeout: time.Second})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Applied {
		t.Fatal("plugin was not applied")
	}
	value, err := manifest.Load(projectDir)
	if err != nil {
		t.Fatal(err)
	}
	if len(value.Plugins) != 1 || value.Plugins[0].Name != "audit" || value.Plugins[0].Checksum == "" {
		t.Fatalf("plugins = %+v", value.Plugins)
	}
	if !contains(value.Features, "plugin:audit:trail") {
		t.Fatalf("features = %v", value.Features)
	}
	record, ok := value.File("internal/audit/audit.gen.go")
	if !ok || record.Producer != "audit" || record.Ownership != "generated" {
		t.Fatalf("plugin record = %+v, %v", record, ok)
	}

	second, err := Run(context.Background(), Options{ProjectDir: projectDir, PluginName: "audit", FrameworkVersion: "1.0.0", Timeout: time.Second})
	if err != nil {
		t.Fatal(err)
	}
	if second.Applied {
		t.Fatal("second plugin run was not idempotent")
	}

	regenerated, err := generator.Generate(generator.Request{Config: config, Destination: projectDir, FrameworkVersion: "1.0.0"})
	if err != nil {
		t.Fatal(err)
	}
	if regenerated.Applied {
		t.Fatal("unchanged core regeneration should not apply")
	}
	value, err = manifest.Load(projectDir)
	if err != nil {
		t.Fatal(err)
	}
	if len(value.Plugins) != 1 || !contains(value.Features, "plugin:audit:trail") {
		t.Fatalf("plugin metadata lost after regeneration: %+v", value)
	}
}

func TestRunRejectsCoreArtifactCollision(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("shell fixture")
	}
	projectDir, _ := generatedProject(t)
	writePlugin(t, projectDir, "audit", `#!/bin/sh
read request
case "$GOSVC_PLUGIN_ACTION" in
  validate) printf '%s\n' '{"protocol_version":1}' ;;
  contribute) printf '%s\n' '{"protocol_version":1,"contribution":{"artifacts":[{"path":"go.mod","content":"malicious\n","mode":420,"ownership":"user"}]}}' ;;
esac
`)
	_, err := Run(context.Background(), Options{ProjectDir: projectDir, PluginName: "audit", FrameworkVersion: "1.0.0", Timeout: time.Second})
	if err == nil || !strings.Contains(err.Error(), "gosvc core") {
		t.Fatalf("Run() error = %v", err)
	}
}

func TestCoreRegenerationRejectsModifiedPluginGeneratedFile(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("shell fixture")
	}
	projectDir, config := generatedProject(t)
	writePlugin(t, projectDir, "audit", `#!/bin/sh
read request
case "$GOSVC_PLUGIN_ACTION" in
  validate) printf '%s\n' '{"protocol_version":1}' ;;
  contribute) printf '%s\n' '{"protocol_version":1,"contribution":{"artifacts":[{"path":"internal/audit/audit.gen.go","content":"package audit\n","mode":420,"ownership":"generated"}]}}' ;;
esac
`)
	if _, err := Run(context.Background(), Options{ProjectDir: projectDir, PluginName: "audit", FrameworkVersion: "1.0.0", Timeout: time.Second}); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(projectDir, "internal", "audit", "audit.gen.go")
	if err := os.WriteFile(path, []byte("package audit\n// modified\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := generator.Generate(generator.Request{Config: config, Destination: projectDir, FrameworkVersion: "1.0.0"})
	if err == nil || !strings.Contains(err.Error(), "rerun plugin") {
		t.Fatalf("Generate() error = %v", err)
	}
}

func generatedProject(t *testing.T) (string, project.Config) {
	t.Helper()
	projectDir := filepath.Join(t.TempDir(), "service")
	config := project.DefaultConfigForPreset("minimal-api")
	config.Project.Name = "service"
	config.Project.Module = "github.com/acme/service"
	if _, err := generator.Generate(generator.Request{Config: config, Destination: projectDir, FrameworkVersion: "1.0.0"}); err != nil {
		t.Fatal(err)
	}
	return projectDir, config
}

func writePlugin(t *testing.T, projectDir, name, script string) {
	t.Helper()
	root := filepath.Join(projectDir, ".gosvc", "plugins", name)
	entrypoint := filepath.Join(root, "bin", "plugin")
	if err := os.MkdirAll(filepath.Dir(entrypoint), 0o755); err != nil {
		t.Fatal(err)
	}
	content := []byte(script)
	if err := os.WriteFile(entrypoint, content, 0o755); err != nil {
		t.Fatal(err)
	}
	metadata := plugin.Metadata{
		SchemaVersion: plugin.CurrentSchemaVersion, ProtocolVersion: plugin.CurrentProtocolVersion,
		Name: name, Version: "1.0.0", Description: "Test plugin",
		MinimumGosvcVersion: "1.0.0",
		Capabilities:        []plugin.Capability{plugin.CapabilityValidation, plugin.CapabilityArtifacts},
		Entrypoint:          "bin/plugin", Checksum: plugin.Checksum(content),
		Execution: plugin.Execution{Mode: plugin.ExecutionNative},
	}
	data, err := json.MarshalIndent(metadata, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "plugin.json"), append(data, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
}

func contains(values []string, expected string) bool {
	for _, value := range values {
		if value == expected {
			return true
		}
	}
	return false
}

func TestRunForceRestoresModifiedGeneratedArtifactButNotUserArtifact(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("shell fixture")
	}
	projectDir, _ := generatedProject(t)
	writePlugin(t, projectDir, "audit", `#!/bin/sh
read request
case "$GOSVC_PLUGIN_ACTION" in
  validate) printf '%s\n' '{"protocol_version":1}' ;;
  contribute) printf '%s\n' '{"protocol_version":1,"contribution":{"artifacts":[{"path":"internal/audit/audit.gen.go","content":"package audit\n","mode":420,"ownership":"generated"},{"path":"docs/AUDIT.md","content":"# Generated suggestion\n","mode":420,"ownership":"user"}]}}' ;;
esac
`)
	if _, err := Run(context.Background(), Options{ProjectDir: projectDir, PluginName: "audit", FrameworkVersion: "1.0.0", Timeout: time.Second}); err != nil {
		t.Fatal(err)
	}
	generated := filepath.Join(projectDir, "internal", "audit", "audit.gen.go")
	userFile := filepath.Join(projectDir, "docs", "AUDIT.md")
	if err := os.WriteFile(generated, []byte("package audit\n// broken\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(userFile, []byte("# My audit documentation\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	result, err := Run(context.Background(), Options{ProjectDir: projectDir, PluginName: "audit", FrameworkVersion: "1.0.0", Timeout: time.Second, Force: true})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Applied {
		t.Fatal("force run did not apply")
	}
	content, err := os.ReadFile(generated)
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != "package audit\n" {
		t.Fatalf("generated artifact not restored: %q", content)
	}
	content, err = os.ReadFile(userFile)
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != "# My audit documentation\n" {
		t.Fatalf("user artifact overwritten: %q", content)
	}
}

func TestProjectValidationDetectsTamperedInstalledPlugin(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("shell fixture")
	}
	projectDir, _ := generatedProject(t)
	writePlugin(t, projectDir, "audit", `#!/bin/sh
read request
case "$GOSVC_PLUGIN_ACTION" in
  validate) printf '%s\n' '{"protocol_version":1}' ;;
  contribute) printf '%s\n' '{"protocol_version":1,"contribution":{"artifacts":[{"path":"internal/audit/audit.gen.go","content":"package audit\n","mode":420,"ownership":"generated"}]}}' ;;
esac
`)
	if _, err := Run(context.Background(), Options{ProjectDir: projectDir, PluginName: "audit", FrameworkVersion: "1.0.0", Timeout: time.Second}); err != nil {
		t.Fatal(err)
	}
	entrypoint := filepath.Join(projectDir, ".gosvc", "plugins", "audit", "bin", "plugin")
	if err := os.WriteFile(entrypoint, []byte("#!/bin/sh\necho tampered\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	report, err := projectcheck.Check(projectDir)
	if err != nil {
		t.Fatal(err)
	}
	if !report.HasErrors() {
		t.Fatalf("tampered plugin was not detected: %+v", report)
	}
	found := false
	for _, issue := range report.Issues {
		if strings.Contains(issue.Message, "checksum") {
			found = true
		}
	}
	if !found {
		t.Fatalf("checksum issue missing: %+v", report.Issues)
	}
}
