package generator

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"

	"github.com/ailtonmacedo/gosvc/internal/project"
	"github.com/ailtonmacedo/gosvc/internal/resource"
)

func renderManagedResources(config project.Config, resources []resource.Definition) ([]Artifact, error) {
	if !config.OpenAPI.Enabled {
		return nil, nil
	}
	values := append([]resource.Definition(nil), resources...)
	sort.Slice(values, func(i, j int) bool { return values[i].Name < values[j].Name })
	registry, err := resource.Encode(values)
	if err != nil {
		return nil, err
	}
	spec := buildOpenAPI(config, values)
	artifacts := []Artifact{
		mustArtifact(resource.RegistryPath, registry, OwnershipGenerated),
		mustArtifact("api/openapi.yaml", []byte(spec), OwnershipGenerated),
		mustArtifact("internal/generated/openapi/spec.gen.go", mustFormat("internal/generated/openapi/spec.gen.go", buildSpecGo(config, spec)), OwnershipGenerated),
		mustArtifact("internal/bootstrap/resources.gen.go", mustFormat("internal/bootstrap/resources.gen.go", buildBootstrapResources(config, values)), OwnershipGenerated),
	}
	for _, definition := range values {
		if definition.Name == "order" {
			continue
		}
		generated, err := buildResourceArtifacts(config, definition, definition.Migration)
		if err != nil {
			return nil, err
		}
		artifacts = append(artifacts, generated...)
	}
	return artifacts, nil
}

func mustArtifact(path string, content []byte, ownership Ownership) Artifact {
	return Artifact{Path: path, Content: append([]byte(nil), content...), Mode: 0o644, Ownership: ownership}
}

func mustFormat(path, source string) []byte {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		panic(fmt.Sprintf("format %s: %v\n%s", path, err, source))
	}
	return formatted
}

func buildSpecGo(config project.Config, spec string) string {
	return fmt.Sprintf(`// Code generated by gosvc. DO NOT EDIT.
package openapi

import "github.com/getkin/kin-openapi/openapi3"

const rawSpec = %q
func RawSpec() []byte { return []byte(rawSpec) }
func GetSwagger() (*openapi3.T, error) { return openapi3.NewLoader().LoadFromData([]byte(rawSpec)) }
`, spec)
}

func buildBootstrapResources(config project.Config, resources []resource.Definition) string {
	var b strings.Builder
	b.WriteString("// Code generated by gosvc. DO NOT EDIT.\npackage bootstrap\n\nimport (\n")
	if config.API.Router == "echo" {
		b.WriteString("\t\"github.com/labstack/echo/v4\"\n\n")
	} else {
		b.WriteString("\t\"github.com/go-chi/chi/v5\"\n")
	}
	if config.Database.CodeGeneration == "sqlc" {
		b.WriteString("\t\"github.com/jackc/pgx/v5/pgxpool\"\n\n")
	}
	fmt.Fprintf(&b, "\t\"%s/internal/application\"\n", config.Project.Module)
	fmt.Fprintf(&b, "\thttpserver \"%s/internal/infrastructure/http\"\n", config.Project.Module)
	fmt.Fprintf(&b, "\t\"%s/internal/infrastructure/persistence/postgres\"\n", config.Project.Module)
	b.WriteString(")\n\n")
	if config.Database.CodeGeneration == "gorm" {
		b.WriteString("func buildAPIRoutes(pool *postgres.Pool) httpserver.RouteRegistrar {\n")
	} else {
		b.WriteString("func buildAPIRoutes(pool *pgxpool.Pool) httpserver.RouteRegistrar {\n")
	}
	for _, d := range resources {
		n := exported(d.Name)
		fmt.Fprintf(&b, "\t%sRepository := postgres.New%sRepository(pool)\n", d.Name, n)
		fmt.Fprintf(&b, "\t%sService := application.New%sService(%sRepository)\n", d.Name, n, d.Name)
		fmt.Fprintf(&b, "\t%sHandler := httpserver.New%sHandler(%sService)\n", d.Name, n, d.Name)
	}
	if config.API.Router == "echo" {
		b.WriteString("\treturn func(router *echo.Group) {\n")
	} else {
		b.WriteString("\treturn func(router chi.Router) {\n")
	}
	for _, d := range resources {
		fmt.Fprintf(&b, "\t\t%sHandler.RegisterRoutes(router)\n", d.Name)
	}
	b.WriteString("\t}\n}\n")
	return b.String()
}

func buildResourceArtifacts(config project.Config, d resource.Definition, migration int) ([]Artifact, error) {
	builders := []struct {
		path, source string
		ownership    Ownership
	}{
		{fmt.Sprintf("internal/domain/%s.go", d.Name), buildDomain(d), OwnershipUser},
		{fmt.Sprintf("internal/domain/%s_errors.go", d.Name), buildErrors(d), OwnershipUser},
		{fmt.Sprintf("internal/ports/%s_repository.go", d.Name), buildPort(config, d), OwnershipUser},
		{fmt.Sprintf("internal/application/%s_service.go", d.Name), buildService(config, d), OwnershipUser},
		{fmt.Sprintf("internal/application/%s_service_test.go", d.Name), buildServiceTest(config, d), OwnershipUser},
		{fmt.Sprintf("db/migrations/%06d_create_%s.up.sql", migration, d.Plural), buildMigrationUp(d), OwnershipUser},
		{fmt.Sprintf("db/migrations/%06d_create_%s.down.sql", migration, d.Plural), fmt.Sprintf("DROP TABLE IF EXISTS %s;\n", d.Plural), OwnershipUser},
	}
	if config.Database.CodeGeneration == "gorm" {
		builders = append(builders,
			struct {
				path, source string
				ownership    Ownership
			}{fmt.Sprintf("internal/infrastructure/persistence/postgres/%s_repository.go", d.Name), buildGORMRepository(config, d), OwnershipUser},
			struct {
				path, source string
				ownership    Ownership
			}{fmt.Sprintf("tests/integration/%s_repository_test.go", d.Name), buildIntegrationTest(config, d), OwnershipUser},
		)
	} else {
		builders = append(builders,
			struct {
				path, source string
				ownership    Ownership
			}{fmt.Sprintf("internal/infrastructure/persistence/postgres/%s_repository.go", d.Name), buildRepository(config, d), OwnershipUser},
			struct {
				path, source string
				ownership    Ownership
			}{fmt.Sprintf("internal/generated/sqlc/%s.sql.go", d.Plural), buildDBGen(d), OwnershipGenerated},
			struct {
				path, source string
				ownership    Ownership
			}{fmt.Sprintf("db/queries/%s.sql", d.Plural), buildQueries(d), OwnershipUser},
			struct {
				path, source string
				ownership    Ownership
			}{fmt.Sprintf("tests/integration/%s_repository_test.go", d.Name), buildIntegrationTest(config, d), OwnershipUser},
		)
	}
	if config.API.Router == "echo" {
		builders = append(builders,
			struct {
				path, source string
				ownership    Ownership
			}{fmt.Sprintf("internal/infrastructure/http/%s_handler.go", d.Name), buildEchoHandler(config, d), OwnershipUser},
			struct {
				path, source string
				ownership    Ownership
			}{fmt.Sprintf("internal/infrastructure/http/%s_handler_test.go", d.Name), buildEchoHandlerTest(config, d), OwnershipUser},
		)
	} else {
		builders = append(builders,
			struct {
				path, source string
				ownership    Ownership
			}{fmt.Sprintf("internal/infrastructure/http/%s_handler.go", d.Name), buildHandler(config, d), OwnershipUser},
			struct {
				path, source string
				ownership    Ownership
			}{fmt.Sprintf("internal/infrastructure/http/%s_handler_test.go", d.Name), buildHandlerTest(config, d), OwnershipUser},
		)
	}
	result := make([]Artifact, 0, len(builders))
	for _, item := range builders {
		content := []byte(item.source)
		if strings.HasSuffix(item.path, ".go") {
			f, err := format.Source(content)
			if err != nil {
				return nil, fmt.Errorf("format generated resource file %s: %w\n%s", item.path, err, content)
			}
			content = f
		}
		result = append(result, mustArtifact(item.path, content, item.ownership))
	}
	return result, nil
}

func buildDomain(d resource.Definition) string {
	var b strings.Builder
	b.WriteString("package domain\n\nimport (\n\t\"time\"\n")
	if hasFieldType(d, "uuid") {
		b.WriteString("\n\t\"github.com/google/uuid\"\n")
	}
	b.WriteString(")\n\n")
	fmt.Fprintf(&b, "type %s struct {\n", exported(d.Name))
	for _, f := range d.Fields {
		fmt.Fprintf(&b, "\t%s %s\n", exported(f.Name), goType(f.Type))
	}
	b.WriteString("\tCreatedAt time.Time\n\tUpdatedAt time.Time\n}\n")
	return b.String()
}

func buildErrors(d resource.Definition) string {
	return fmt.Sprintf("package domain\n\nimport \"errors\"\n\nvar Err%sNotFound = errors.New(%q)\n", exported(d.Name), d.Name+" not found")
}
func buildPort(config project.Config, d resource.Definition) string {
	n := exported(d.Name)
	id := goType(d.ID().Type)
	var b strings.Builder
	b.WriteString("package ports\n\nimport (\n\t\"context\"\n")
	if d.ID().Type == "uuid" {
		b.WriteString("\n\t\"github.com/google/uuid\"\n")
	}
	fmt.Fprintf(&b, "\n\t%q\n)\n\n", config.Project.Module+"/internal/domain")
	fmt.Fprintf(&b, "type %sRepository interface {\n", n)
	fmt.Fprintf(&b, "\tCreate(context.Context, domain.%s) (domain.%s, error)\n", n, n)
	fmt.Fprintf(&b, "\tGetByID(context.Context, %s) (domain.%s, error)\n", id, n)
	fmt.Fprintf(&b, "\tList(context.Context, int32, int32) ([]domain.%s, error)\n", n)
	fmt.Fprintf(&b, "\tUpdate(context.Context, domain.%s) (domain.%s, error)\n", n, n)
	fmt.Fprintf(&b, "\tDelete(context.Context, %s) error\n", id)
	b.WriteString("}\n")
	return b.String()
}

func buildService(config project.Config, d resource.Definition) string {
	n := exported(d.Name)
	id := goType(d.ID().Type)
	var b strings.Builder
	b.WriteString("package application\n\nimport (\n\t\"context\"\n\t\"fmt\"\n")
	if d.ID().Type == "uuid" {
		b.WriteString("\n\t\"github.com/google/uuid\"\n")
	}
	fmt.Fprintf(&b, "\n\t%q\n\t%q\n)\n\n", config.Project.Module+"/internal/domain", config.Project.Module+"/internal/ports")
	fmt.Fprintf(&b, "type %sService struct { repository ports.%sRepository }\n", n, n)
	fmt.Fprintf(&b, "func New%sService(repository ports.%sRepository) *%sService { return &%sService{repository: repository} }\n", n, n, n, n)
	fmt.Fprintf(&b, "func (s *%sService) Create(ctx context.Context, value domain.%s) (domain.%s, error) { created, err := s.repository.Create(ctx, value); if err != nil { return domain.%s{}, fmt.Errorf(\"create %s: %%w\", err) }; return created, nil }\n", n, n, n, n, d.Name)
	fmt.Fprintf(&b, "func (s *%sService) GetByID(ctx context.Context, id %s) (domain.%s, error) { value, err := s.repository.GetByID(ctx, id); if err != nil { return domain.%s{}, fmt.Errorf(\"get %s: %%w\", err) }; return value, nil }\n", n, id, n, n, d.Name)
	fmt.Fprintf(&b, "func (s *%sService) List(ctx context.Context, limit, offset int32) ([]domain.%s, error) { values, err := s.repository.List(ctx, limit, offset); if err != nil { return nil, fmt.Errorf(\"list %s: %%w\", err) }; return values, nil }\n", n, n, d.Plural)
	fmt.Fprintf(&b, "func (s *%sService) Update(ctx context.Context, value domain.%s) (domain.%s, error) { updated, err := s.repository.Update(ctx, value); if err != nil { return domain.%s{}, fmt.Errorf(\"update %s: %%w\", err) }; return updated, nil }\n", n, n, n, n, d.Name)
	fmt.Fprintf(&b, "func (s *%sService) Delete(ctx context.Context, id %s) error { if err := s.repository.Delete(ctx, id); err != nil { return fmt.Errorf(\"delete %s: %%w\", err) }; return nil }\n", n, id, d.Name)
	return b.String()
}

func buildRepository(config project.Config, d resource.Definition) string {
	n := exported(d.Name)
	id := goType(d.ID().Type)
	var b strings.Builder
	b.WriteString("package postgres\n\nimport (\n\t\"context\"\n\t\"errors\"\n\t\"fmt\"\n\n")
	if d.ID().Type == "uuid" {
		b.WriteString("\t\"github.com/google/uuid\"\n")
	}
	b.WriteString("\t\"github.com/jackc/pgx/v5\"\n\n")
	fmt.Fprintf(&b, "\t%q\n", config.Project.Module+"/internal/domain")
	fmt.Fprintf(&b, "\tdbgen %q\n", config.Project.Module+"/internal/generated/sqlc")
	fmt.Fprintf(&b, "\t%q\n)\n\n", config.Project.Module+"/internal/ports")
	fmt.Fprintf(&b, "var _ ports.%sRepository = (*%sRepository)(nil)\n\n", n, n)
	fmt.Fprintf(&b, "type %sRepository struct { queries *dbgen.Queries }\n", n)
	fmt.Fprintf(&b, "func New%sRepository(db dbgen.DBTX) *%sRepository { return &%sRepository{queries: dbgen.New(db)} }\n", n, n, n)
	fmt.Fprintf(&b, "func (r *%sRepository) Create(ctx context.Context, value domain.%s) (domain.%s, error) { created, err := r.queries.Create%s(ctx, toCreate%sParams(value)); if err != nil { return domain.%s{}, fmt.Errorf(\"insert %s: %%w\", err) }; return toDomain%s(created), nil }\n", n, n, n, n, n, n, d.Name, n)
	fmt.Fprintf(&b, "func (r *%sRepository) GetByID(ctx context.Context, id %s) (domain.%s, error) { value, err := r.queries.Get%s(ctx, id); if errors.Is(err, pgx.ErrNoRows) { return domain.%s{}, domain.Err%sNotFound }; if err != nil { return domain.%s{}, fmt.Errorf(\"select %s: %%w\", err) }; return toDomain%s(value), nil }\n", n, id, n, n, n, n, n, d.Name, n)
	fmt.Fprintf(&b, "func (r *%sRepository) List(ctx context.Context, limit, offset int32) ([]domain.%s, error) { items, err := r.queries.List%s(ctx, dbgen.List%sParams{Limit: limit, Offset: offset}); if err != nil { return nil, fmt.Errorf(\"list %s: %%w\", err) }; result := make([]domain.%s, 0, len(items)); for _, value := range items { result = append(result, toDomain%s(value)) }; return result, nil }\n", n, n, n, n, d.Plural, n, n)
	fmt.Fprintf(&b, "func (r *%sRepository) Update(ctx context.Context, value domain.%s) (domain.%s, error) { updated, err := r.queries.Update%s(ctx, toUpdate%sParams(value)); if errors.Is(err, pgx.ErrNoRows) { return domain.%s{}, domain.Err%sNotFound }; if err != nil { return domain.%s{}, fmt.Errorf(\"update %s: %%w\", err) }; return toDomain%s(updated), nil }\n", n, n, n, n, n, n, n, n, d.Name, n)
	fmt.Fprintf(&b, "func (r *%sRepository) Delete(ctx context.Context, id %s) error { _, err := r.queries.Delete%s(ctx, id); if errors.Is(err, pgx.ErrNoRows) { return domain.Err%sNotFound }; if err != nil { return fmt.Errorf(\"delete %s: %%w\", err) }; return nil }\n", n, id, n, n, d.Name)
	b.WriteString(buildRepositoryMappers(d))
	return b.String()
}

func buildRepositoryMappers(d resource.Definition) string {
	n := exported(d.Name)
	var b strings.Builder
	fmt.Fprintf(&b, "\nfunc toDomain%s(v dbgen.%s) domain.%s{return domain.%s{", n, n, n, n)
	for _, f := range d.Fields {
		if f.Type == "datetime" {
			fmt.Fprintf(&b, "%s:timeFromDB(v.%s),", exported(f.Name), exported(f.Name))
			continue
		}
		fmt.Fprintf(&b, "%s:v.%s,", exported(f.Name), exported(f.Name))
	}
	b.WriteString("CreatedAt:timeFromDB(v.CreatedAt),UpdatedAt:timeFromDB(v.UpdatedAt)}}\n")
	fmt.Fprintf(&b, "func toCreate%sParams(v domain.%s) dbgen.Create%sParams{return dbgen.Create%sParams{", n, n, n, n)
	for _, f := range createFields(d) {
		if f.Type == "datetime" {
			fmt.Fprintf(&b, "%s:timeToDB(v.%s),", exported(f.Name), exported(f.Name))
			continue
		}
		fmt.Fprintf(&b, "%s:v.%s,", exported(f.Name), exported(f.Name))
	}
	b.WriteString("}}\n")
	fmt.Fprintf(&b, "func toUpdate%sParams(v domain.%s) dbgen.Update%sParams{return dbgen.Update%sParams{", n, n, n, n)
	for _, f := range d.Fields {
		if f.Type == "datetime" {
			fmt.Fprintf(&b, "%s:timeToDB(v.%s),", exported(f.Name), exported(f.Name))
			continue
		}
		fmt.Fprintf(&b, "%s:v.%s,", exported(f.Name), exported(f.Name))
	}
	b.WriteString("}}\n")
	return b.String()
}

func buildDBGen(d resource.Definition) string {
	n := exported(d.Name)
	var b strings.Builder
	b.WriteString("// Code generated by sqlc-compatible gosvc snapshot. DO NOT EDIT.\npackage dbgen\n\nimport (\n\t\"context\"\n\n\t\"github.com/jackc/pgx/v5/pgtype\"\n")
	if hasFieldType(d, "uuid") {
		b.WriteString("\n\t\"github.com/google/uuid\"\n")
	}
	b.WriteString(")\n")
	fmt.Fprintf(&b, "type %s struct{", n)
	for _, f := range d.Fields {
		fmt.Fprintf(&b, "%s %s;", exported(f.Name), dbGoType(f.Type))
	}
	b.WriteString("CreatedAt pgtype.Timestamptz;UpdatedAt pgtype.Timestamptz}\n")
	fmt.Fprintf(&b, "type Create%sParams struct{", n)
	for _, f := range createFields(d) {
		fmt.Fprintf(&b, "%s %s;", exported(f.Name), dbGoType(f.Type))
	}
	b.WriteString("}\n")
	fmt.Fprintf(&b, "type Update%sParams struct{", n)
	for _, f := range d.Fields {
		fmt.Fprintf(&b, "%s %s;", exported(f.Name), dbGoType(f.Type))
	}
	b.WriteString("}\n")
	fmt.Fprintf(&b, "type List%sParams struct{Limit int32;Offset int32}\n", n)
	cols := columnNames(d.Fields)
	create := createFields(d)
	ccols := columnNames(create)
	placeholders := make([]string, len(create))
	for i := range placeholders {
		placeholders[i] = fmt.Sprintf("$%d", i+1)
	}
	fmt.Fprintf(&b, "const create%s=%q\n", n, fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s) RETURNING %s, created_at, updated_at", d.Plural, strings.Join(ccols, ", "), strings.Join(placeholders, ", "), strings.Join(cols, ", ")))
	fmt.Fprintf(&b, "func(q *Queries)Create%s(ctx context.Context,arg Create%sParams)(%s,error){row:=q.db.QueryRow(ctx,create%s", n, n, n, n)
	for _, f := range create {
		fmt.Fprintf(&b, ",arg.%s", exported(f.Name))
	}
	fmt.Fprintf(&b, ");var v %s;err:=row.Scan(%s);return v,err}\n", n, scanArgs(d, "v"))
	fmt.Fprintf(&b, "func(q *Queries)Get%s(ctx context.Context,id %s)(%s,error){row:=q.db.QueryRow(ctx,%q,id);var v %s;err:=row.Scan(%s);return v,err}\n", n, goType(d.ID().Type), n, fmt.Sprintf("SELECT %s, created_at, updated_at FROM %s WHERE id = $1", strings.Join(cols, ", "), d.Plural), n, scanArgs(d, "v"))
	fmt.Fprintf(&b, "func(q *Queries)List%s(ctx context.Context,arg List%sParams)([]%s,error){rows,err:=q.db.Query(ctx,%q,arg.Limit,arg.Offset);if err!=nil{return nil,err};defer rows.Close();items:=make([]%s,0);for rows.Next(){var v %s;if err:=rows.Scan(%s);err!=nil{return nil,err};items=append(items,v)};if err:=rows.Err();err!=nil{return nil,err};return items,nil}\n", n, n, n, fmt.Sprintf("SELECT %s, created_at, updated_at FROM %s ORDER BY id LIMIT $1 OFFSET $2", strings.Join(cols, ", "), d.Plural), n, n, scanArgs(d, "v"))
	sets := []string{}
	for i, f := range create {
		sets = append(sets, fmt.Sprintf("%s = $%d", f.Name, i+2))
	}
	fmt.Fprintf(&b, "func(q *Queries)Update%s(ctx context.Context,arg Update%sParams)(%s,error){row:=q.db.QueryRow(ctx,%q,arg.ID", n, n, n, fmt.Sprintf("UPDATE %s SET %s, updated_at = NOW() WHERE id = $1 RETURNING %s, created_at, updated_at", d.Plural, strings.Join(sets, ", "), strings.Join(cols, ", ")))
	for _, f := range create {
		fmt.Fprintf(&b, ",arg.%s", exported(f.Name))
	}
	fmt.Fprintf(&b, ");var v %s;err:=row.Scan(%s);return v,err}\n", n, scanArgs(d, "v"))
	fmt.Fprintf(&b, "func(q *Queries)Delete%s(ctx context.Context,id %s)(%s,error){row:=q.db.QueryRow(ctx,%q,id);var deleted %s;err:=row.Scan(&deleted);return deleted,err}\n", n, goType(d.ID().Type), goType(d.ID().Type), fmt.Sprintf("DELETE FROM %s WHERE id = $1 RETURNING id", d.Plural), goType(d.ID().Type))
	return b.String()
}

func buildGORMRepository(config project.Config, d resource.Definition) string {
	n := exported(d.Name)
	id := goType(d.ID().Type)
	var b strings.Builder
	b.WriteString("package postgres\n\nimport (\n\t\"context\"\n\t\"errors\"\n\t\"fmt\"\n\n")
	if d.ID().Type == "uuid" {
		b.WriteString("\t\"github.com/google/uuid\"\n")
	}
	if hasFieldType(d, "datetime") {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\t\"gorm.io/gorm\"\n\n")
	fmt.Fprintf(&b, "\t%q\n\t%q\n)\n\n", config.Project.Module+"/internal/domain", config.Project.Module+"/internal/ports")
	fmt.Fprintf(&b, "var _ ports.%sRepository = (*%sRepository)(nil)\n", n, n)
	fmt.Fprintf(&b, "type %sRepository struct{db *gorm.DB}\n", n)
	fmt.Fprintf(&b, "func New%sRepository(pool *Pool)*%sRepository{return &%sRepository{db:pool.DB}}\n", n, n, n)
	fmt.Fprintf(&b, "func(r *%sRepository)Create(ctx context.Context,value domain.%s)(domain.%s,error){if err:=r.db.WithContext(ctx).Table(%q).Omit(\"ID\").Create(&value).Error;err!=nil{return domain.%s{},fmt.Errorf(\"insert %s: %%w\",err)};return value,nil}\n", n, n, n, d.Plural, n, d.Name)
	fmt.Fprintf(&b, "func(r *%sRepository)GetByID(ctx context.Context,id %s)(domain.%s,error){var value domain.%s;err:=r.db.WithContext(ctx).Table(%q).Where(\"id = ?\",id).First(&value).Error;if errors.Is(err,gorm.ErrRecordNotFound){return domain.%s{},domain.Err%sNotFound};if err!=nil{return domain.%s{},fmt.Errorf(\"select %s: %%w\",err)};return value,nil}\n", n, id, n, n, d.Plural, n, n, n, d.Name)
	fmt.Fprintf(&b, "func(r *%sRepository)List(ctx context.Context,limit,offset int32)([]domain.%s,error){var values []domain.%s;if err:=r.db.WithContext(ctx).Table(%q).Order(\"id\").Limit(int(limit)).Offset(int(offset)).Find(&values).Error;err!=nil{return nil,fmt.Errorf(\"list %s: %%w\",err)};return values,nil}\n", n, n, n, d.Plural, d.Plural)
	fmt.Fprintf(&b, "func(r *%sRepository)Update(ctx context.Context,value domain.%s)(domain.%s,error){result:=r.db.WithContext(ctx).Table(%q).Where(\"id = ?\",value.ID).Updates(&value);if result.Error!=nil{return domain.%s{},fmt.Errorf(\"update %s: %%w\",result.Error)};if result.RowsAffected==0{return domain.%s{},domain.Err%sNotFound};return r.GetByID(ctx,value.ID)}\n", n, n, n, d.Plural, n, d.Name, n, n)
	fmt.Fprintf(&b, "func(r *%sRepository)Delete(ctx context.Context,id %s)error{result:=r.db.WithContext(ctx).Table(%q).Where(\"id = ?\",id).Delete(&domain.%s{});if result.Error!=nil{return fmt.Errorf(\"delete %s: %%w\",result.Error)};if result.RowsAffected==0{return domain.Err%sNotFound};return nil}\n", n, id, d.Plural, n, d.Name, n)
	if d.ID().Type == "uuid" {
		b.WriteString("var _ = uuid.Nil\n")
	}
	if hasFieldType(d, "datetime") {
		b.WriteString("var _ = time.Time{}\n")
	}
	return b.String()
}

func buildEchoHandler(config project.Config, d resource.Definition) string {
	n := exported(d.Name)
	id := goType(d.ID().Type)
	var b strings.Builder
	b.WriteString("package httpserver\n\nimport (\n\t\"context\"\n\t\"errors\"\n\t\"net/http\"\n\t\"strconv\"\n\t\"time\"\n\n\t\"github.com/labstack/echo/v4\"\n")
	if hasFieldType(d, "uuid") {
		b.WriteString("\t\"github.com/google/uuid\"\n")
	}
	fmt.Fprintf(&b, "\n\t%q\n)\n\n", config.Project.Module+"/internal/domain")
	fmt.Fprintf(&b, "type %sUseCase interface{Create(context.Context,domain.%s)(domain.%s,error);GetByID(context.Context,%s)(domain.%s,error);List(context.Context,int32,int32)([]domain.%s,error);Update(context.Context,domain.%s)(domain.%s,error);Delete(context.Context,%s)error}\n", n, n, n, id, n, n, n, n, id)
	fmt.Fprintf(&b, "type %sHandler struct{service %sUseCase};func New%sHandler(s %sUseCase)*%sHandler{return &%sHandler{service:s}}\n", n, n, n, n, n, n)
	fmt.Fprintf(&b, "func(h *%sHandler)RegisterRoutes(r *echo.Group){r.GET(%q,h.list);r.POST(%q,h.create);r.GET(%q,h.get);r.PUT(%q,h.update);r.DELETE(%q,h.delete)}\n", n, "/"+d.Plural, "/"+d.Plural, "/"+d.Plural+"/:id", "/"+d.Plural+"/:id", "/"+d.Plural+"/:id")
	fmt.Fprintf(&b, "type %sPayload struct{", d.Name)
	for _, f := range createFields(d) {
		fmt.Fprintf(&b, "%s %s `json:\"%s\"`;", exported(f.Name), goType(f.Type), f.Name)
	}
	b.WriteString("}\n")
	fmt.Fprintf(&b, "func(h *%sHandler)create(c echo.Context)error{var in %sPayload;if err:=c.Bind(&in);err!=nil{return apiError(c,400,\"invalid_json\",\"Invalid JSON body.\")};v:=domain.%s{", n, d.Name, n)
	for _, f := range createFields(d) {
		fmt.Fprintf(&b, "%s:in.%s,", exported(f.Name), exported(f.Name))
	}
	fmt.Fprintf(&b, "};created,err:=h.service.Create(c.Request().Context(),v);if err!=nil{return h.writeError(c,err)};return c.JSON(201,%sResponse(created))}\n", d.Name)
	fmt.Fprintf(&b, "func(h *%sHandler)list(c echo.Context)error{items,err:=h.service.List(c.Request().Context(),50,0);if err!=nil{return h.writeError(c,err)};result:=make([]map[string]any,0,len(items));for _,v:=range items{result=append(result,%sResponse(v))};return c.JSON(200,map[string]any{\"items\":result})}\n", n, d.Name)
	fmt.Fprintf(&b, "func(h *%sHandler)get(c echo.Context)error{id,ok:=%sEchoID(c);if !ok{return nil};v,err:=h.service.GetByID(c.Request().Context(),id);if err!=nil{return h.writeError(c,err)};return c.JSON(200,%sResponse(v))}\n", n, d.Name, d.Name)
	fmt.Fprintf(&b, "func(h *%sHandler)update(c echo.Context)error{id,ok:=%sEchoID(c);if !ok{return nil};var in %sPayload;if err:=c.Bind(&in);err!=nil{return apiError(c,400,\"invalid_json\",\"Invalid JSON body.\")};v:=domain.%s{ID:id,", n, d.Name, d.Name, n)
	for _, f := range createFields(d) {
		fmt.Fprintf(&b, "%s:in.%s,", exported(f.Name), exported(f.Name))
	}
	fmt.Fprintf(&b, "};updated,err:=h.service.Update(c.Request().Context(),v);if err!=nil{return h.writeError(c,err)};return c.JSON(200,%sResponse(updated))}\n", d.Name)
	fmt.Fprintf(&b, "func(h *%sHandler)delete(c echo.Context)error{id,ok:=%sEchoID(c);if !ok{return nil};if err:=h.service.Delete(c.Request().Context(),id);err!=nil{return h.writeError(c,err)};return c.NoContent(204)}\n", n, d.Name)
	if d.ID().Type == "int64" {
		fmt.Fprintf(&b, "func %sEchoID(c echo.Context)(int64,bool){id,err:=strconv.ParseInt(c.Param(\"id\"),10,64);if err!=nil||id<1{_ = apiError(c,400,\"invalid_id\",\"Invalid id.\");return 0,false};return id,true}\n", d.Name)
	} else {
		fmt.Fprintf(&b, "func %sEchoID(c echo.Context)(uuid.UUID,bool){id,err:=uuid.Parse(c.Param(\"id\"));if err!=nil{_ = apiError(c,400,\"invalid_id\",\"Invalid id.\");return uuid.Nil,false};return id,true}\n", d.Name)
	}
	fmt.Fprintf(&b, "func(h *%sHandler)writeError(c echo.Context,err error)error{if errors.Is(err,domain.Err%sNotFound){return apiError(c,404,%q,%q)};return apiError(c,500,\"internal_error\",\"Internal server error.\")}\n", n, n, d.Name+"_not_found", n+" not found.")
	fmt.Fprintf(&b, "func %sResponse(v domain.%s)map[string]any{return map[string]any{", d.Name, n)
	for _, f := range d.Fields {
		fmt.Fprintf(&b, "%q:v.%s,", f.Name, exported(f.Name))
	}
	b.WriteString("\"created_at\":v.CreatedAt,\"updated_at\":v.UpdatedAt}}\nvar _=http.StatusOK\nvar _=strconv.IntSize\nvar _=time.Time{}\n")
	return b.String()
}

func buildEchoHandlerTest(config project.Config, d resource.Definition) string {
	n := exported(d.Name)
	idType := goType(d.ID().Type)
	pathID := "1"
	if d.ID().Type == "uuid" {
		pathID = "00000000-0000-0000-0000-000000000001"
	}
	valid := sampleJSONPayload(d)
	var b strings.Builder
	b.WriteString("package httpserver\n\nimport(\"context\";\"net/http\";\"net/http/httptest\";\"strings\";\"testing\";\"github.com/labstack/echo/v4\"")
	if hasFieldType(d, "uuid") {
		b.WriteString(";\"github.com/google/uuid\"")
	}
	if hasFieldType(d, "datetime") {
		b.WriteString(";\"time\"")
	}
	fmt.Fprintf(&b, ";%q)\n", config.Project.Module+"/internal/domain")
	fmt.Fprintf(&b, "type fake%sUseCase struct{create domain.%s;get domain.%s;list []domain.%s;update domain.%s}\n", n, n, n, n, n)
	fmt.Fprintf(&b, "func(f fake%sUseCase)Create(context.Context,domain.%s)(domain.%s,error){return f.create,nil}\n", n, n, n)
	fmt.Fprintf(&b, "func(f fake%sUseCase)GetByID(context.Context,%s)(domain.%s,error){return f.get,nil}\n", n, idType, n)
	fmt.Fprintf(&b, "func(f fake%sUseCase)List(context.Context,int32,int32)([]domain.%s,error){return f.list,nil}\n", n, n)
	fmt.Fprintf(&b, "func(f fake%sUseCase)Update(context.Context,domain.%s)(domain.%s,error){return f.update,nil}\n", n, n, n)
	fmt.Fprintf(&b, "func(f fake%sUseCase)Delete(context.Context,%s)error{return nil}\n", n, idType)
	fmt.Fprintf(&b, "func Test%sEchoHandler(t *testing.T){t.Parallel();tests:=[]struct{method,path,body string;want int}{{http.MethodPost,%q,%q,201},{http.MethodGet,%q,\"\",200},{http.MethodGet,%q,\"\",400}};for _,tt:=range tests{e:=echo.New();g:=e.Group(\"\");New%sHandler(fake%sUseCase{create:%s,get:%s}).RegisterRoutes(g);req:=httptest.NewRequest(tt.method,tt.path,strings.NewReader(tt.body));req.Header.Set(echo.HeaderContentType,echo.MIMEApplicationJSON);res:=httptest.NewRecorder();e.ServeHTTP(res,req);if res.Code!=tt.want{t.Fatalf(\"status=%%d want=%%d body=%%s\",res.Code,tt.want,res.Body.String())}}}\n", n, "/"+d.Plural, valid, "/"+d.Plural+"/"+pathID, "/"+d.Plural+"/invalid", n, n, sampleDomainValue(d, true), sampleDomainValue(d, true))
	return b.String()
}

func buildHandler(config project.Config, d resource.Definition) string {
	n := exported(d.Name)
	id := goType(d.ID().Type)
	var b strings.Builder
	b.WriteString("package httpserver\n\nimport (\n\t\"context\"\n\t\"encoding/json\"\n\t\"errors\"\n\t\"net/http\"\n\t\"strconv\"\n\t\"time\"\n\n\t\"github.com/go-chi/chi/v5\"\n")
	if hasFieldType(d, "uuid") {
		b.WriteString("\t\"github.com/google/uuid\"\n")
	}
	fmt.Fprintf(&b, "\n\t%q\n)\n\n", config.Project.Module+"/internal/domain")
	fmt.Fprintf(&b, "type %sUseCase interface{Create(context.Context,domain.%s)(domain.%s,error);GetByID(context.Context,%s)(domain.%s,error);List(context.Context,int32,int32)([]domain.%s,error);Update(context.Context,domain.%s)(domain.%s,error);Delete(context.Context,%s)error}\n", n, n, n, id, n, n, n, n, id)
	fmt.Fprintf(&b, "type %sHandler struct{service %sUseCase}\nfunc New%sHandler(s %sUseCase)*%sHandler{return &%sHandler{service:s}}\n", n, n, n, n, n, n)
	fmt.Fprintf(&b, "func(h *%sHandler)RegisterRoutes(r chi.Router){r.Get(%q,h.list);r.Post(%q,h.create);r.Get(%q,h.get);r.Put(%q,h.update);r.Delete(%q,h.delete)}\n", n, "/"+d.Plural, "/"+d.Plural, "/"+d.Plural+"/{id}", "/"+d.Plural+"/{id}", "/"+d.Plural+"/{id}")
	fmt.Fprintf(&b, "type %sPayload struct{", d.Name)
	for _, f := range createFields(d) {
		fmt.Fprintf(&b, "%s %s `json:\"%s\"`;", exported(f.Name), goType(f.Type), f.Name)
	}
	b.WriteString("}\n")
	fmt.Fprintf(&b, "func(h *%sHandler)create(w http.ResponseWriter,r *http.Request){var in %sPayload;if json.NewDecoder(r.Body).Decode(&in)!=nil{writeAPIError(w,r,400,\"invalid_json\",\"Invalid JSON body.\");return};v:=domain.%s{", n, d.Name, n)
	for _, f := range createFields(d) {
		fmt.Fprintf(&b, "%s:in.%s,", exported(f.Name), exported(f.Name))
	}
	fmt.Fprintf(&b, "};created,err:=h.service.Create(r.Context(),v);if err!=nil{h.writeError(w,r,err);return};writeJSON(w,201,%sResponse(created))}\n", d.Name)
	fmt.Fprintf(&b, "func(h *%sHandler)list(w http.ResponseWriter,r *http.Request){items,err:=h.service.List(r.Context(),50,0);if err!=nil{h.writeError(w,r,err);return};result:=make([]map[string]any,0,len(items));for _,v:=range items{result=append(result,%sResponse(v))};writeJSON(w,200,map[string]any{\"items\":result})}\n", n, d.Name)
	fmt.Fprintf(&b, "func(h *%sHandler)get(w http.ResponseWriter,r *http.Request){id,ok:=%sID(w,r);if !ok{return};v,err:=h.service.GetByID(r.Context(),id);if err!=nil{h.writeError(w,r,err);return};writeJSON(w,200,%sResponse(v))}\n", n, d.Name, d.Name)
	fmt.Fprintf(&b, "func(h *%sHandler)update(w http.ResponseWriter,r *http.Request){id,ok:=%sID(w,r);if !ok{return};var in %sPayload;if json.NewDecoder(r.Body).Decode(&in)!=nil{writeAPIError(w,r,400,\"invalid_json\",\"Invalid JSON body.\");return};v:=domain.%s{ID:id,", n, d.Name, d.Name, n)
	for _, f := range createFields(d) {
		fmt.Fprintf(&b, "%s:in.%s,", exported(f.Name), exported(f.Name))
	}
	fmt.Fprintf(&b, "};updated,err:=h.service.Update(r.Context(),v);if err!=nil{h.writeError(w,r,err);return};writeJSON(w,200,%sResponse(updated))}\n", d.Name)
	fmt.Fprintf(&b, "func(h *%sHandler)delete(w http.ResponseWriter,r *http.Request){id,ok:=%sID(w,r);if !ok{return};if err:=h.service.Delete(r.Context(),id);err!=nil{h.writeError(w,r,err);return};w.WriteHeader(204)}\n", n, d.Name)
	if d.ID().Type == "int64" {
		fmt.Fprintf(&b, "func %sID(w http.ResponseWriter,r *http.Request)(int64,bool){id,err:=strconv.ParseInt(chi.URLParam(r,\"id\"),10,64);if err!=nil||id<1{writeAPIError(w,r,400,\"invalid_id\",\"Invalid id.\");return 0,false};return id,true}\n", d.Name)
	} else {
		fmt.Fprintf(&b, "func %sID(w http.ResponseWriter,r *http.Request)(uuid.UUID,bool){id,err:=uuid.Parse(chi.URLParam(r,\"id\"));if err!=nil{writeAPIError(w,r,400,\"invalid_id\",\"Invalid id.\");return uuid.Nil,false};return id,true}\n", d.Name)
	}
	fmt.Fprintf(&b, "func(h *%sHandler)writeError(w http.ResponseWriter,r *http.Request,err error){if errors.Is(err,domain.Err%sNotFound){writeAPIError(w,r,404,%q,%q);return};writeAPIError(w,r,500,\"internal_error\",\"Internal server error.\")}\n", n, n, d.Name+"_not_found", n+" not found.")
	fmt.Fprintf(&b, "func %sResponse(v domain.%s)map[string]any{return map[string]any{", d.Name, n)
	for _, f := range d.Fields {
		fmt.Fprintf(&b, "%q:v.%s,", f.Name, exported(f.Name))
	}
	b.WriteString("\"created_at\":v.CreatedAt,\"updated_at\":v.UpdatedAt}}\n")
	b.WriteString("var _ = strconv.IntSize\nvar _ = time.Time{}\n")
	return b.String()
}

func buildHandlerTest(config project.Config, d resource.Definition) string {
	n := exported(d.Name)
	idType := goType(d.ID().Type)
	pathID := "1"
	if d.ID().Type == "uuid" {
		pathID = "00000000-0000-0000-0000-000000000001"
	}
	validBody := sampleJSONPayload(d)
	var b strings.Builder
	b.WriteString("package httpserver\n\nimport (\n\t\"context\"\n\t\"errors\"\n\t\"net/http\"\n\t\"net/http/httptest\"\n\t\"strings\"\n\t\"testing\"\n")
	if hasFieldType(d, "uuid") {
		b.WriteString("\n\t\"github.com/google/uuid\"\n")
	}
	if hasFieldType(d, "datetime") {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n\t\"github.com/go-chi/chi/v5\"\n")
	fmt.Fprintf(&b, "\n\t%q\n)\n\n", config.Project.Module+"/internal/domain")
	fmt.Fprintf(&b, "type fake%sUseCase struct{create domain.%s;get domain.%s;list []domain.%s;update domain.%s;createErr error;getErr error;listErr error;updateErr error;deleteErr error}\n", n, n, n, n, n)
	fmt.Fprintf(&b, "func(f fake%sUseCase)Create(context.Context,domain.%s)(domain.%s,error){return f.create,f.createErr}\n", n, n, n)
	fmt.Fprintf(&b, "func(f fake%sUseCase)GetByID(context.Context,%s)(domain.%s,error){return f.get,f.getErr}\n", n, idType, n)
	fmt.Fprintf(&b, "func(f fake%sUseCase)List(context.Context,int32,int32)([]domain.%s,error){return f.list,f.listErr}\n", n, n)
	fmt.Fprintf(&b, "func(f fake%sUseCase)Update(context.Context,domain.%s)(domain.%s,error){return f.update,f.updateErr}\n", n, n, n)
	fmt.Fprintf(&b, "func(f fake%sUseCase)Delete(context.Context,%s)error{return f.deleteErr}\n", n, idType)
	sample := sampleDomainValue(d, true)
	fmt.Fprintf(&b, "func Test%sHandler(t *testing.T){t.Parallel();internal:=errors.New(\"internal\");sample:=%s;tests:=[]struct{name,method,path,body string;service %sUseCase;want int}{", n, sample, n)
	fmt.Fprintf(&b, "{name:\"create\",method:http.MethodPost,path:%q,body:%q,service:fake%sUseCase{create:sample},want:http.StatusCreated},", "/"+d.Plural, validBody, n)
	fmt.Fprintf(&b, "{name:\"create invalid json\",method:http.MethodPost,path:%q,body:\"{\",service:fake%sUseCase{},want:http.StatusBadRequest},", "/"+d.Plural, n)
	fmt.Fprintf(&b, "{name:\"create internal\",method:http.MethodPost,path:%q,body:%q,service:fake%sUseCase{createErr:internal},want:http.StatusInternalServerError},", "/"+d.Plural, validBody, n)
	fmt.Fprintf(&b, "{name:\"list\",method:http.MethodGet,path:%q,service:fake%sUseCase{list:[]domain.%s{sample}},want:http.StatusOK},", "/"+d.Plural, n, n)
	fmt.Fprintf(&b, "{name:\"list error\",method:http.MethodGet,path:%q,service:fake%sUseCase{listErr:internal},want:http.StatusInternalServerError},", "/"+d.Plural, n)
	fmt.Fprintf(&b, "{name:\"get\",method:http.MethodGet,path:%q,service:fake%sUseCase{get:sample},want:http.StatusOK},", "/"+d.Plural+"/"+pathID, n)
	fmt.Fprintf(&b, "{name:\"invalid id\",method:http.MethodGet,path:%q,service:fake%sUseCase{},want:http.StatusBadRequest},", "/"+d.Plural+"/invalid", n)
	fmt.Fprintf(&b, "{name:\"get not found\",method:http.MethodGet,path:%q,service:fake%sUseCase{getErr:domain.Err%sNotFound},want:http.StatusNotFound},", "/"+d.Plural+"/"+pathID, n, n)
	fmt.Fprintf(&b, "{name:\"update\",method:http.MethodPut,path:%q,body:%q,service:fake%sUseCase{update:sample},want:http.StatusOK},", "/"+d.Plural+"/"+pathID, validBody, n)
	fmt.Fprintf(&b, "{name:\"update invalid json\",method:http.MethodPut,path:%q,body:\"{\",service:fake%sUseCase{},want:http.StatusBadRequest},", "/"+d.Plural+"/"+pathID, n)
	fmt.Fprintf(&b, "{name:\"update not found\",method:http.MethodPut,path:%q,body:%q,service:fake%sUseCase{updateErr:domain.Err%sNotFound},want:http.StatusNotFound},", "/"+d.Plural+"/"+pathID, validBody, n, n)
	fmt.Fprintf(&b, "{name:\"delete\",method:http.MethodDelete,path:%q,service:fake%sUseCase{},want:http.StatusNoContent},", "/"+d.Plural+"/"+pathID, n)
	fmt.Fprintf(&b, "{name:\"delete not found\",method:http.MethodDelete,path:%q,service:fake%sUseCase{deleteErr:domain.Err%sNotFound},want:http.StatusNotFound},", "/"+d.Plural+"/"+pathID, n, n)
	fmt.Fprintf(&b, "};for _,test:=range tests{test:=test;t.Run(test.name,func(t *testing.T){t.Parallel();router:=chi.NewRouter();New%sHandler(test.service).RegisterRoutes(router);request:=httptest.NewRequest(test.method,test.path,strings.NewReader(test.body));response:=httptest.NewRecorder();router.ServeHTTP(response,request);if response.Code!=test.want{t.Fatalf(\"status=%%d want=%%d body=%%s\",response.Code,test.want,response.Body.String())}})}}\n", n)
	return b.String()
}

func buildQueries(d resource.Definition) string {
	n := exported(d.Name)
	cols := columnNames(d.Fields)
	create := createFields(d)
	ccols := columnNames(create)
	ph := []string{}
	for i := range create {
		ph = append(ph, fmt.Sprintf("$%d", i+1))
	}
	sets := []string{}
	for i, f := range create {
		sets = append(sets, fmt.Sprintf("%s = $%d", f.Name, i+2))
	}
	return fmt.Sprintf("-- name: Create%s :one\nINSERT INTO %s (%s) VALUES (%s) RETURNING %s, created_at, updated_at;\n\n-- name: Get%s :one\nSELECT %s, created_at, updated_at FROM %s WHERE id = $1;\n\n-- name: List%s :many\nSELECT %s, created_at, updated_at FROM %s ORDER BY id LIMIT $1 OFFSET $2;\n\n-- name: Update%s :one\nUPDATE %s SET %s, updated_at = NOW() WHERE id = $1 RETURNING %s, created_at, updated_at;\n\n-- name: Delete%s :one\nDELETE FROM %s WHERE id = $1 RETURNING id;\n", n, d.Plural, strings.Join(ccols, ", "), strings.Join(ph, ", "), strings.Join(cols, ", "), n, strings.Join(cols, ", "), d.Plural, n, strings.Join(cols, ", "), d.Plural, n, d.Plural, strings.Join(sets, ", "), strings.Join(cols, ", "), n, d.Plural)
}
func buildMigrationUp(d resource.Definition) string {
	var b strings.Builder
	if d.ID().Type == "uuid" {
		b.WriteString("CREATE EXTENSION IF NOT EXISTS pgcrypto;\n\n")
	}
	fmt.Fprintf(&b, "CREATE TABLE %s (\n", d.Plural)
	for i, f := range d.Fields {
		suffix := ","
		if i == len(d.Fields)-1 {
			suffix = ","
		}
		fmt.Fprintf(&b, "    %s %s%s\n", f.Name, sqlType(f, true), suffix)
	}
	b.WriteString("    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n")
	return b.String()
}

func buildOpenAPI(config project.Config, resources []resource.Definition) string {
	var b strings.Builder
	fmt.Fprintf(&b, "openapi: 3.0.3\ninfo:\n  title: %s API\n  version: 1.0.0\n", config.Project.Name)
	if config.Auth.Enabled {
		b.WriteString("security:\n  - bearerAuth: []\n")
	}
	b.WriteString("paths:\n")
	if config.Auth.Enabled {
		b.WriteString("  /auth/login:\n    post:\n      operationId: login\n      security: []\n      requestBody:\n        required: true\n        content:\n          application/json:\n            schema:\n              $ref: '#/components/schemas/LoginRequest'\n      responses:\n        '200': { description: Authenticated, content: { application/json: { schema: { $ref: '#/components/schemas/TokenResponse' } } } }\n        '401': { description: Invalid credentials, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }\n  /auth/refresh:\n    post:\n      operationId: refreshToken\n      security: []\n      responses:\n        '200': { description: Refreshed, content: { application/json: { schema: { $ref: '#/components/schemas/TokenResponse' } } } }\n        '401': { description: Invalid refresh token, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }\n  /auth/logout:\n    post:\n      operationId: logout\n      security: []\n      responses:\n        '204': { description: Logged out }\n  /admin/ping:\n    get:\n      operationId: adminPing\n      security:\n        - bearerAuth: []\n      responses:\n        '200': { description: Administrative health response }\n        '401': { description: Unauthenticated, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }\n        '403': { description: Forbidden, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }\n")
	}
	for _, d := range resources {
		n := exported(d.Name)
		fmt.Fprintf(&b, "  /%s:\n    get:\n      operationId: list%s\n      responses:\n        '200':\n          description: %s list\n          content:\n            application/json:\n              schema:\n                $ref: '#/components/schemas/%sList'\n    post:\n      operationId: create%s\n      requestBody:\n        required: true\n        content:\n          application/json:\n            schema:\n              $ref: '#/components/schemas/Create%s'\n      responses:\n        '201':\n          description: Created\n          content:\n            application/json:\n              schema:\n                $ref: '#/components/schemas/%s'\n  /%s/{id}:\n    parameters:\n      - name: id\n        in: path\n        required: true\n        schema:\n%s    get:\n      operationId: get%s\n      responses:\n        '200': { description: Found, content: { application/json: { schema: { $ref: '#/components/schemas/%s' } } } }\n        '404': { description: Not found, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }\n    put:\n      operationId: update%s\n      requestBody: { required: true, content: { application/json: { schema: { $ref: '#/components/schemas/Create%s' } } } }\n      responses:\n        '200': { description: Updated, content: { application/json: { schema: { $ref: '#/components/schemas/%s' } } } }\n    delete:\n      operationId: delete%s\n      responses:\n        '204': { description: Deleted }\n", d.Plural, exported(d.Plural), n, n, n, n, n, d.Plural, openAPIYAMLType(d.ID().Type, 10), n, n, n, n, n, n)
	}
	b.WriteString("components:\n")
	if config.Auth.Enabled {
		b.WriteString("  securitySchemes:\n    bearerAuth:\n      type: http\n      scheme: bearer\n      bearerFormat: JWT\n")
	}
	b.WriteString("  schemas:\n    Error:\n      type: object\n      required: [code, message]\n      properties:\n        code: { type: string }\n        message: { type: string }\n        request_id: { type: string }\n")
	if config.Auth.Enabled {
		b.WriteString("    LoginRequest:\n      type: object\n      required: [email, password]\n      properties:\n        email: { type: string, format: email }\n        password: { type: string, format: password, minLength: 8 }\n    TokenResponse:\n      type: object\n      required: [access_token, token_type, expires_at]\n      properties:\n        access_token: { type: string }\n        token_type: { type: string, example: Bearer }\n        expires_at: { type: string, format: date-time }\n")
	}
	for _, d := range resources {
		n := exported(d.Name)
		fmt.Fprintf(&b, "    %s:\n      type: object\n      required: [", n)
		req := []string{}
		for _, f := range d.Fields {
			req = append(req, f.Name)
		}
		req = append(req, "created_at", "updated_at")
		b.WriteString(strings.Join(req, ", ") + "]\n      properties:\n")
		for _, f := range d.Fields {
			fmt.Fprintf(&b, "        %s:\n%s", f.Name, openAPIYAMLType(f.Type, 10))
		}
		b.WriteString("        created_at: { type: string, format: date-time }\n        updated_at: { type: string, format: date-time }\n")
		fmt.Fprintf(&b, "    Create%s:\n      type: object\n      required: [", n)
		req = []string{}
		for _, f := range createFields(d) {
			req = append(req, f.Name)
		}
		b.WriteString(strings.Join(req, ", ") + "]\n      properties:\n")
		for _, f := range createFields(d) {
			fmt.Fprintf(&b, "        %s:\n%s", f.Name, openAPIYAMLType(f.Type, 10))
		}
		fmt.Fprintf(&b, "    %sList:\n      type: object\n      required: [items]\n      properties:\n        items:\n          type: array\n          items: { $ref: '#/components/schemas/%s' }\n", n, n)
	}
	return b.String()
}

func openAPIYAMLType(t string, indent int) string {
	pad := strings.Repeat(" ", indent)
	switch t {
	case "int64":
		return pad + "type: integer\n" + pad + "format: int64\n"
	case "bool":
		return pad + "type: boolean\n"
	case "datetime":
		return pad + "type: string\n" + pad + "format: date-time\n"
	case "uuid":
		return pad + "type: string\n" + pad + "format: uuid\n"
	default:
		return pad + "type: string\n"
	}
}
func goType(t string) string {
	switch t {
	case "uuid":
		return "uuid.UUID"
	case "int64":
		return "int64"
	case "bool":
		return "bool"
	case "datetime":
		return "time.Time"
	default:
		return "string"
	}
}

func dbGoType(t string) string {
	if t == "datetime" {
		return "pgtype.Timestamptz"
	}
	return goType(t)
}

func hasFieldType(d resource.Definition, fieldType string) bool {
	for _, field := range d.Fields {
		if field.Type == fieldType {
			return true
		}
	}
	return false
}

func openAPIGoType(t string) string { return goType(t) }
func sqlType(f resource.Field, primary bool) string {
	if f.Name == "id" && primary {
		if f.Type == "int64" {
			return "BIGSERIAL PRIMARY KEY"
		}
		if f.Type == "uuid" {
			return "UUID PRIMARY KEY DEFAULT gen_random_uuid()"
		}
		return "TEXT PRIMARY KEY"
	}
	switch f.Type {
	case "int64":
		return "BIGINT NOT NULL"
	case "bool":
		return "BOOLEAN NOT NULL"
	case "datetime":
		return "TIMESTAMPTZ NOT NULL"
	case "uuid":
		return "UUID NOT NULL"
	default:
		return "TEXT NOT NULL"
	}
}
func createFields(d resource.Definition) []resource.Field {
	r := []resource.Field{}
	for _, f := range d.Fields {
		if f.Name != "id" {
			r = append(r, f)
		}
	}
	return r
}
func columnNames(fields []resource.Field) []string {
	r := make([]string, len(fields))
	for i, f := range fields {
		r[i] = f.Name
	}
	return r
}
func scanArgs(d resource.Definition, v string) string {
	r := []string{}
	for _, f := range d.Fields {
		r = append(r, "&"+v+"."+exported(f.Name))
	}
	r = append(r, "&"+v+".CreatedAt", "&"+v+".UpdatedAt")
	return strings.Join(r, ",")
}
func exported(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool { return r == '_' || r == '-' })
	for i, part := range parts {
		switch strings.ToLower(part) {
		case "id":
			parts[i] = "ID"
		case "url":
			parts[i] = "URL"
		case "api":
			parts[i] = "API"
		default:
			runes := []rune(part)
			if len(runes) > 0 {
				runes[0] = unicode.ToUpper(runes[0])
			}
			parts[i] = string(runes)
		}
	}
	return strings.Join(parts, "")
}

func buildServiceTest(config project.Config, d resource.Definition) string {
	n := exported(d.Name)
	idType := goType(d.ID().Type)
	var b strings.Builder
	b.WriteString("package application\n\nimport (\n\t\"context\"\n\t\"errors\"\n\t\"reflect\"\n\t\"testing\"\n")
	if hasFieldType(d, "uuid") {
		b.WriteString("\n\t\"github.com/google/uuid\"\n")
	}
	if hasFieldType(d, "datetime") {
		b.WriteString("\t\"time\"\n")
	}
	fmt.Fprintf(&b, "\n\t%q\n)\n\n", config.Project.Module+"/internal/domain")
	fmt.Fprintf(&b, "type %sRepositoryStub struct{createResult domain.%s;getResult domain.%s;listResult []domain.%s;updateResult domain.%s;createErr error;getErr error;listErr error;updateErr error;deleteErr error}\n", d.Name, n, n, n, n)
	fmt.Fprintf(&b, "func(s %sRepositoryStub)Create(context.Context,domain.%s)(domain.%s,error){return s.createResult,s.createErr}\n", d.Name, n, n)
	fmt.Fprintf(&b, "func(s %sRepositoryStub)GetByID(context.Context,%s)(domain.%s,error){return s.getResult,s.getErr}\n", d.Name, idType, n)
	fmt.Fprintf(&b, "func(s %sRepositoryStub)List(context.Context,int32,int32)([]domain.%s,error){return s.listResult,s.listErr}\n", d.Name, n)
	fmt.Fprintf(&b, "func(s %sRepositoryStub)Update(context.Context,domain.%s)(domain.%s,error){return s.updateResult,s.updateErr}\n", d.Name, n, n)
	fmt.Fprintf(&b, "func(s %sRepositoryStub)Delete(context.Context,%s)error{return s.deleteErr}\n", d.Name, idType)
	sample := sampleDomainValue(d, true)
	idExpr := "expected.ID"
	fmt.Fprintf(&b, "func Test%sService(t *testing.T){t.Parallel();sentinel:=errors.New(\"repository unavailable\");expected:=%s;", n, sample)
	fmt.Fprintf(&b, "t.Run(\"create success\",func(t *testing.T){value,err:=New%sService(%sRepositoryStub{createResult:expected}).Create(context.Background(),domain.%s{});if err!=nil||!reflect.DeepEqual(value,expected){t.Fatalf(\"value=%%+v err=%%v\",value,err)}});", n, d.Name, n)
	fmt.Fprintf(&b, "t.Run(\"create error\",func(t *testing.T){_,err:=New%sService(%sRepositoryStub{createErr:sentinel}).Create(context.Background(),domain.%s{});if !errors.Is(err,sentinel){t.Fatalf(\"error=%%v\",err)}});", n, d.Name, n)
	fmt.Fprintf(&b, "t.Run(\"get success\",func(t *testing.T){value,err:=New%sService(%sRepositoryStub{getResult:expected}).GetByID(context.Background(),%s);if err!=nil||!reflect.DeepEqual(value,expected){t.Fatalf(\"value=%%+v err=%%v\",value,err)}});", n, d.Name, idExpr)
	fmt.Fprintf(&b, "t.Run(\"get error\",func(t *testing.T){_,err:=New%sService(%sRepositoryStub{getErr:sentinel}).GetByID(context.Background(),%s);if !errors.Is(err,sentinel){t.Fatalf(\"error=%%v\",err)}});", n, d.Name, idExpr)
	fmt.Fprintf(&b, "t.Run(\"list success\",func(t *testing.T){values,err:=New%sService(%sRepositoryStub{listResult:[]domain.%s{expected}}).List(context.Background(),10,0);if err!=nil||len(values)!=1{t.Fatalf(\"values=%%+v err=%%v\",values,err)}});", n, d.Name, n)
	fmt.Fprintf(&b, "t.Run(\"list error\",func(t *testing.T){_,err:=New%sService(%sRepositoryStub{listErr:sentinel}).List(context.Background(),10,0);if !errors.Is(err,sentinel){t.Fatalf(\"error=%%v\",err)}});", n, d.Name)
	fmt.Fprintf(&b, "t.Run(\"update success\",func(t *testing.T){value,err:=New%sService(%sRepositoryStub{updateResult:expected}).Update(context.Background(),expected);if err!=nil||!reflect.DeepEqual(value,expected){t.Fatalf(\"value=%%+v err=%%v\",value,err)}});", n, d.Name)
	fmt.Fprintf(&b, "t.Run(\"update error\",func(t *testing.T){_,err:=New%sService(%sRepositoryStub{updateErr:sentinel}).Update(context.Background(),expected);if !errors.Is(err,sentinel){t.Fatalf(\"error=%%v\",err)}});", n, d.Name)
	fmt.Fprintf(&b, "t.Run(\"delete success\",func(t *testing.T){if err:=New%sService(%sRepositoryStub{}).Delete(context.Background(),%s);err!=nil{t.Fatal(err)}});", n, d.Name, idExpr)
	fmt.Fprintf(&b, "t.Run(\"delete error\",func(t *testing.T){if err:=New%sService(%sRepositoryStub{deleteErr:sentinel}).Delete(context.Background(),%s);!errors.Is(err,sentinel){t.Fatalf(\"error=%%v\",err)}})}\n", n, d.Name, idExpr)
	return b.String()
}

func buildIntegrationTest(config project.Config, d resource.Definition) string {
	n := exported(d.Name)
	var b strings.Builder
	b.WriteString("//go:build integration\n\npackage integration\n\nimport (\n\t\"context\"\n\t\"os\"\n\t\"testing\"\n\t\"time\"\n")
	if hasFieldType(d, "uuid") {
		b.WriteString("\n\t\"github.com/google/uuid\"\n")
	}
	fmt.Fprintf(&b, "\n\t%q\n\t%q\n\t%q\n)\n\n", config.Project.Module+"/internal/config", config.Project.Module+"/internal/domain", config.Project.Module+"/internal/infrastructure/persistence/postgres")
	fmt.Fprintf(&b, "func Test%sRepository(t *testing.T){url:=os.Getenv(\"DATABASE_URL\");if url==\"\"{t.Skip(\"DATABASE_URL is not set\")};ctx,cancel:=context.WithTimeout(context.Background(),10*time.Second);t.Cleanup(cancel);pool,err:=postgres.OpenPool(ctx,config.DatabaseConfig{Enabled:true,URL:url,MaxConns:4,MaxConnLifetime:time.Minute,MaxConnIdleTime:time.Minute,HealthCheckPeriod:time.Minute,QueryTimeout:3*time.Second});if err!=nil{t.Fatal(err)};t.Cleanup(pool.Close);repository:=postgres.New%sRepository(pool);created,err:=repository.Create(ctx,%s);if err!=nil{t.Fatal(err)};", n, n, sampleDomainValue(d, false))
	if d.ID().Type == "uuid" {
		b.WriteString("if created.ID==uuid.Nil{t.Fatal(\"created ID is nil\")};")
	} else {
		b.WriteString("if created.ID==0{t.Fatal(\"created ID is zero\")};")
	}
	b.WriteString("loaded,err:=repository.GetByID(ctx,created.ID);if err!=nil{t.Fatal(err)};if loaded.ID!=created.ID{t.Fatalf(\"loaded ID does not match created ID\")};if err:=repository.Delete(ctx,created.ID);err!=nil{t.Fatal(err)}}\n")
	return b.String()
}

func sampleJSONPayload(d resource.Definition) string {
	parts := make([]string, 0)
	for index, field := range createFields(d) {
		var value string
		switch field.Type {
		case "uuid":
			value = fmt.Sprintf("\"00000000-0000-0000-0000-%012d\"", index+1)
		case "int64":
			value = fmt.Sprintf("%d", (index+1)*100)
		case "bool":
			value = "true"
		case "datetime":
			value = "\"2026-01-01T00:00:00Z\""
		default:
			value = fmt.Sprintf("%q", field.Name+"-sample")
		}
		parts = append(parts, fmt.Sprintf("%q:%s", field.Name, value))
	}
	return "{" + strings.Join(parts, ",") + "}"
}

func sampleDomainValue(d resource.Definition, withID bool) string {
	var b strings.Builder
	fmt.Fprintf(&b, "domain.%s{", exported(d.Name))
	for index, field := range d.Fields {
		if field.Name == "id" && !withID {
			continue
		}
		value := sampleGoValue(field, index)
		fmt.Fprintf(&b, "%s:%s,", exported(field.Name), value)
	}
	b.WriteString("}")
	return b.String()
}

func sampleGoValue(field resource.Field, index int) string {
	switch field.Type {
	case "uuid":
		return fmt.Sprintf("uuid.UUID{%d}", index+1)
	case "int64":
		return fmt.Sprintf("%d", (index+1)*100)
	case "bool":
		return "true"
	case "datetime":
		return fmt.Sprintf("time.Unix(%d,0).UTC()", index+1)
	default:
		return fmt.Sprintf("%q", field.Name+"-sample")
	}
}
